import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Nav from './ui/nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} bg-black text-white`}>
				<header className='shadow-sm shadow-[#ffffff79] p-8'>
					<Nav />
				</header>
				<main className='px-4 sm:px-8'>{children}</main>
			</body>
		</html>
	);
}
